<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class AdNetworkSettingRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'app_id' => ['nullable'],
            'app_db_id' => ['nullable', 'integer', 'exists:apps,id'],
            'app_package_name' => ['nullable', 'string'],
            'app_name' => ['nullable', 'string'],
            'package_name' => ['nullable', 'string'],
            'current_version' => ['nullable', 'string'],
            'is_active' => ['boolean'],
            'ad_show_status' => ['boolean'],
            'admob_status' => ['boolean'],
            'admob_app_id' => ['nullable', 'string', 'max:255'],
            'admob_banner_id' => ['nullable', 'string', 'max:255'],
            'admob_medium_rectangle_id' => ['nullable', 'string', 'max:255'],
            'admob_interstitial_id' => ['nullable', 'string', 'max:255'],
            'admob_native_id' => ['nullable', 'string', 'max:255'],
            'admob_rewarded_id' => ['nullable', 'string', 'max:255'],
            'admob_app_open_id' => ['nullable', 'string', 'max:255'],
            'adx_inter_id' => ['nullable', 'string', 'max:255'],
            'adx_banner_id' => ['nullable', 'string', 'max:255'],
            'adx_medium_rectangle_id' => ['nullable', 'string', 'max:255'],
            'adx_native_id' => ['nullable', 'string', 'max:255'],
            'adx_app_open_id' => ['nullable', 'string', 'max:255'],
            'fb_inter_id' => ['nullable', 'string', 'max:255'],
            'fb_banner_id' => ['nullable', 'string', 'max:255'],
            'fb_medium_rectangle_id' => ['nullable', 'string', 'max:255'],
            'fb_native_id' => ['nullable', 'string', 'max:255'],
            'fb_native_banner_id' => ['nullable', 'string', 'max:255'],
            'wortise_app_id' => ['nullable', 'string', 'max:255'],
            'wortise_app_open_id' => ['nullable', 'string', 'max:255'],
            'wortise_inter_id' => ['nullable', 'string', 'max:255'],
            'wortise_banner_id' => ['nullable', 'string', 'max:255'],
            'wortise_medium_rectangle_id' => ['nullable', 'string', 'max:255'],
            'wortise_native_id' => ['nullable', 'string', 'max:255'],
            'admob_interid' => ['nullable', 'string', 'max:255'],
            'admob_bannerid' => ['nullable', 'string', 'max:255'],
            'admob_medium_rectangleid' => ['nullable', 'string', 'max:255'],
            'admob_nativeid' => ['nullable', 'string', 'max:255'],
            'admob_appopenid' => ['nullable', 'string', 'max:255'],
            'adx_medium_rectangleid' => ['nullable', 'string', 'max:255'],
            'adx_appopen_id' => ['nullable', 'string', 'max:255'],
            'wortise_appopen_id' => ['nullable', 'string', 'max:255'],
            'how_show_ad' => ['nullable', 'integer', 'in:0,1'],
            'ad_platform_sequence' => ['nullable', 'string', 'max:255'],
            'alternate_ad_show' => ['nullable', 'string', 'max:255'],
            'main_click_count' => ['nullable', 'integer', 'min:0'],
            'inner_click_count' => ['nullable', 'integer', 'min:0'],
            'inter_count' => ['nullable', 'integer', 'min:0'],
            'ad_splash' => ['nullable', 'string', 'max:255'],
            'ad_inter' => ['nullable', 'string', 'max:255'],
            'ad_appopen' => ['nullable', 'string', 'max:255'],
            'ad_native' => ['nullable', 'string', 'max:255'],
            'ad_small_native' => ['nullable', 'string', 'max:255'],
            'ad_banner' => ['nullable', 'string', 'max:255'],
            'ad_qureka' => ['nullable', 'string', 'max:255'],
            'dialog_before_ad_show' => ['boolean'],
            'dialog_time_seconds' => ['nullable', 'integer', 'min:0', 'max:60'],
            'need_internet' => ['boolean'],
            'redirect_other_app_status' => ['boolean'],
            'new_package_name' => ['nullable', 'string', 'max:255'],
            'redirect_app' => ['nullable', 'string', 'max:255'],
            'new_app_name' => ['nullable', 'string', 'max:255'],
            'new_app_icon' => ['nullable', 'string', 'max:255'],
            'new_app_banner' => ['nullable', 'string', 'max:255'],
            'new_app_body' => ['nullable', 'string'],
            'new_app_link' => ['nullable', 'string', 'max:2048'],
            'download_status' => ['nullable', 'string', 'max:32'],
            'background_status' => ['nullable', 'string', 'max:32'],
            'popup_status' => ['nullable', 'string', 'max:32'],
            'main_click_status' => ['nullable', 'string', 'max:32'],
            'Download' => ['nullable', 'string', 'max:32'],
            'Backgraound' => ['nullable', 'string', 'max:32'],
            'Background' => ['nullable', 'string', 'max:32'],
            'Popup' => ['nullable', 'string', 'max:32'],
            'Main_click' => ['nullable', 'string', 'max:32'],
            'update_dialog_status' => ['boolean'],
            'version_codes' => ['nullable', 'string', 'max:255'],
            'privacy_policy_url' => ['nullable', 'url', 'max:2048'],
            'privacy_url' => ['nullable', 'url', 'max:2048'],
            'more_app_url' => ['nullable', 'url', 'max:2048'],
            'others' => ['nullable', 'array'],
            'others.*.key' => ['nullable', 'string', 'max:255'],
            'others.*.value' => ['nullable', 'string', 'max:1000'],
        ];
    }
}
